In [6]:
import pandas as pd
import numpy as np
import scipy.stats as spicy

In [7]:
df = pd.read_csv("https://raw.githubusercontent.com/roualdes/data/refs/heads/master/penguins.csv")

In [8]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [9]:
xbar = np.mean(df["bill_length_mm"])
s = np.std(df["bill_length_mm"])
N = np.sum(~df["bill_length_mm"].isna())
t = spicy.t(df = N - 1).ppf([0.025, 0.975]) # ppf(0.975)
xbar + t * s / np.sqrt(N)

array([43.34209692, 44.50176273])

In [10]:
np.shape(df)

(344, 8)

In [11]:
N

342

In [41]:
gdf = df.groupby(["sex", "island"], as_index = False)

In [42]:
for name, grouped_df in gdf:
    print(name)
    print(np.mean(grouped_df["bill_length_mm"]))

('female', 'Biscoe')
43.30749999999999
('female', 'Dream')
42.29672131147541
('female', 'Torgersen')
37.55416666666667
('male', 'Biscoe')
47.11927710843374
('male', 'Dream')
46.116129032258065
('male', 'Torgersen')
40.58695652173913

In [43]:
sdf = gdf.aggregate(mn = ("bill_length_mm", np.mean),
                   sd = ("bill_length_mm", np.std))
                   # creates a new grouped dataframe 
                   # based on given parameters, where
                   # parameters follow this pattern
                   # name_var = (col_name, function)

In [44]:
sdf

      sex     island         mn        sd
0  female     Biscoe  43.307500  4.151439
1  female      Dream  42.296721  5.488288
2  female  Torgersen  37.554167  2.161400
3    male     Biscoe  47.119277  4.662655
4    male      Dream  46.116129  5.720512
5    male  Torgersen  40.586957  2.960949